trigger:
- master

jobs:
- job: xplat
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macos-latest'

  pool:
    vmImage: $(imageName)

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'Install-Module ModuleBuilder -Force -SkipPublisherCheck'

  - task: PowerShell@2
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/build.ps1'

- job: windows
  dependsOn: xplat
  condition: succeeded()

  strategy:
    matrix:
      windows:
        imageName: 'windows-latest'
  pool:
    vmImage: $(imageName)
    
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'Install-Module ModuleBuilder -Force -SkipPublisherCheck'

  - task: PowerShell@2
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/build.ps1'

  - publish: $(System.DefaultWorkingDirectory)/Output
    artifact: O365ServiceCommunications
