trigger:
- master

jobs:
- job: xplat
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macos-latest'
      windows:
        imageName: 'windows-latest'

  pool:
    vmImage: $(imageName)

  steps:
  - pwsh: |
      Install-Module ModuleBuilder -Force -SkipPublisherCheck
      & "$(System.DefaultWorkingDirectory)/Build.ps1"
    displayName: Build project
