trigger:
- master

jobs:
- job: xplat
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macos-latest'
      windows:
        imageName: 'windows-latest'

  pool:
    vmImage: $(imageName)

  steps:
  - task: PowerShell@2
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/build.ps1'
